// SHARED_DATA/impresoras_hds.js — impresoras del HDS (3 tipos) desde el archivo Comodatos y
// Traslados HDS-ING (Junio 2026). GENERADO por _DEV/build_impresoras_hds.py — no editar a mano.
window.IMPRESORAS_HDS = {
 "generado": "2026-09-21",
 "fuente": "Comodatos y Traslados HDS-ING (Junio 2026).xlsx · hoja Comodatos (HDS + AMBOS)",
 "nota": "Cantidad = total del código de recinto; el Atlas la reparte entre sus cajas dibujadas por PMA/BIM.",
 "tipos": [
  {
   "k": "mono",
   "nombre": "Impresora Láser Monousuario",
   "ico": "👤",
   "corto": "Láser monousuario"
  },
  {
   "k": "multi",
   "nombre": "Impresora Láser Multiusuario",
   "ico": "👥",
   "corto": "Láser multiusuario"
  },
  {
   "k": "mfp",
   "nombre": "Impresora Multifuncional Multiusuario",
   "ico": "📠",
   "corto": "Multifuncional multiusuario"
  }
 ],
 "totales": {
  "mono": 313,
  "multi": 150,
  "mfp": 172
 },
 "filas": [
  {
   "fila": 254,
   "est": "HDS",
   "recinto": "ARCHIVOS DE FICHAS CLINICAS HDS",
   "cod": "80.11",
   "alt": [],
   "cod_orig": "80.11",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha punto de red"
  },
  {
   "fila": 255,
   "est": "HDS",
   "recinto": "Recepción y Devolución fichas",
   "cod": "80.1",
   "alt": [
    "80.5"
   ],
   "cod_orig": "80.1/80.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 256,
   "est": "HDS",
   "recinto": "Oficina Jefe Archivo",
   "cod": "80.2",
   "alt": [],
   "cod_orig": "80.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 257,
   "est": "HDS",
   "recinto": "Preparación de fichas",
   "cod": "80.4",
   "alt": [],
   "cod_orig": "80.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 258,
   "est": "HDS",
   "recinto": "Secretaría Admisión",
   "cod": "3.1.2",
   "alt": [],
   "cod_orig": "3.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 259,
   "est": "HDS",
   "recinto": "Consulta Médica",
   "cod": "3.2.1",
   "alt": [],
   "cod_orig": "3.2.1",
   "tipo": "mono",
   "cant": 11,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 260,
   "est": "HDS",
   "recinto": "Box Consulta Enfermería",
   "cod": "3.2.2",
   "alt": [],
   "cod_orig": "3.2.2",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 261,
   "est": "HDS",
   "recinto": "Box Consulta Nutrición",
   "cod": "3.2.4",
   "alt": [],
   "cod_orig": "3.2.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 262,
   "est": "HDS",
   "recinto": "Secretaría/Adm./ Recaudación A.4",
   "cod": "4.1.2",
   "alt": [],
   "cod_orig": "4.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 263,
   "est": "HDS",
   "recinto": "Consulta Médica",
   "cod": "4.2.1",
   "alt": [],
   "cod_orig": "4.2.1",
   "tipo": "mono",
   "cant": 11,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 264,
   "est": "HDS",
   "recinto": "Box Consulta Enfermería",
   "cod": "4.2.2",
   "alt": [],
   "cod_orig": "4.2.2",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 265,
   "est": "HDS",
   "recinto": "Secretaría/Adm./ Recaudación A.5",
   "cod": "5.1.2",
   "alt": [],
   "cod_orig": "5.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 266,
   "est": "HDS",
   "recinto": "Box Atención",
   "cod": "5.2.1",
   "alt": [],
   "cod_orig": "5.2.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 267,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "5.2.4",
   "alt": [],
   "cod_orig": "5.2.4",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 268,
   "est": "HDS",
   "recinto": "Secretaría/Adm./ Recaudación A.9",
   "cod": "9.1.2",
   "alt": [],
   "cod_orig": "9.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 269,
   "est": "HDS",
   "recinto": "Informes",
   "cod": "9.1.3",
   "alt": [],
   "cod_orig": "9.1.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 270,
   "est": "HDS",
   "recinto": "Consulta Enfermería",
   "cod": "9.2.1",
   "alt": [],
   "cod_orig": "9.2.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 271,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "9.2.2",
   "alt": [],
   "cod_orig": "9.2.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 272,
   "est": "HDS",
   "recinto": "Marcapasos",
   "cod": "9.2.9",
   "alt": [],
   "cod_orig": "9.2.9",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 273,
   "est": "HDS",
   "recinto": "Consulta Cardiología",
   "cod": "9.2.12",
   "alt": [],
   "cod_orig": "9.2.12",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 274,
   "est": "HDS",
   "recinto": "Módulo Secretaría Administrativa",
   "cod": "15.1.3",
   "alt": [],
   "cod_orig": "15.1.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 275,
   "est": "HDS",
   "recinto": "Oficina Médico Jefe",
   "cod": "15.1.4",
   "alt": [],
   "cod_orig": "15.1.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 276,
   "est": "HDS",
   "recinto": "Estación de Trabajo Profesionales",
   "cod": "15.1.6",
   "alt": [],
   "cod_orig": "15.1.6",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha de Enchufe"
  },
  {
   "fila": 277,
   "est": "HDS",
   "recinto": "Consulta Médica",
   "cod": "15.2.3",
   "alt": [],
   "cod_orig": "15.2.3",
   "tipo": "mono",
   "cant": 4,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 278,
   "est": "HDS",
   "recinto": "Enfermeria",
   "cod": "15.2.4",
   "alt": [],
   "cod_orig": "15.2.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 279,
   "est": "HDS",
   "recinto": "Gimnasio Común",
   "cod": "15.2.9",
   "alt": [],
   "cod_orig": "15.2.9",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha de Enchufe"
  },
  {
   "fila": 280,
   "est": "HDS",
   "recinto": "Gimnasio  Pacientes Neurologicos",
   "cod": "15.2.12",
   "alt": [],
   "cod_orig": "15.2.12",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 281,
   "est": "HDS",
   "recinto": "Oficina Neurología",
   "cod": "15.2.12A",
   "alt": [],
   "cod_orig": "15.2.12A",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 282,
   "est": "HDS",
   "recinto": "Box Consulta Ter. Ocup. Neurología",
   "cod": "15.2.21",
   "alt": [],
   "cod_orig": "15.2.21",
   "tipo": "mono",
   "cant": 4,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 283,
   "est": "HDS",
   "recinto": "Box Terapia Ocupacional",
   "cod": "15.2.22",
   "alt": [],
   "cod_orig": "15.2.22",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 284,
   "est": "HDS",
   "recinto": "Tratamiento Terapia Ocupacional",
   "cod": "15.2.24",
   "alt": [],
   "cod_orig": "15.2.24",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 285,
   "est": "HDS",
   "recinto": "Secretaría/Adm. /Recaudación",
   "cod": "18.1.2",
   "alt": [],
   "cod_orig": "18.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 286,
   "est": "HDS",
   "recinto": "Box Farmacéutico",
   "cod": "18.2.1",
   "alt": [],
   "cod_orig": "18.2.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 287,
   "est": "HDS",
   "recinto": "Entrega Medicamentos",
   "cod": "18.2.2",
   "alt": [],
   "cod_orig": "18.2.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 288,
   "est": "HDS",
   "recinto": "Consulta Médica",
   "cod": "18.2.5",
   "alt": [],
   "cod_orig": "18.2.5",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 289,
   "est": "HDS",
   "recinto": "Consulta Médica",
   "cod": "18.2.6",
   "alt": [],
   "cod_orig": "18.2.6",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 290,
   "est": "HDS",
   "recinto": "Box Consulta Enfermería",
   "cod": "18.2.7",
   "alt": [],
   "cod_orig": "18.2.7",
   "tipo": "mono",
   "cant": 5,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 291,
   "est": "HDS",
   "recinto": "Box Nutrición",
   "cod": "18.2.8",
   "alt": [],
   "cod_orig": "18.2.8",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 292,
   "est": "HDS",
   "recinto": "Box Multifuncional Psicologa A.Social",
   "cod": "18.2.9",
   "alt": [],
   "cod_orig": "18.2.9",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 293,
   "est": "HDS",
   "recinto": "Admisión/ Sec",
   "cod": "19.1.2",
   "alt": [],
   "cod_orig": "19.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 294,
   "est": "HDS",
   "recinto": "Oficina Jefatura",
   "cod": "19.1.4",
   "alt": [],
   "cod_orig": "19.1.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 295,
   "est": "HDS",
   "recinto": "Box Consulta Diferenciado",
   "cod": "19.2.3",
   "alt": [],
   "cod_orig": "19.2.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 296,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "19.2.4",
   "alt": [],
   "cod_orig": "19.2.4",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 297,
   "est": "HDS",
   "recinto": "Box Enfermería",
   "cod": "19.2.16",
   "alt": [],
   "cod_orig": "19.2.16",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 298,
   "est": "HDS",
   "recinto": "Box Consulta Médica",
   "cod": "19.2.17",
   "alt": [],
   "cod_orig": "19.2.17",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 299,
   "est": "HDS",
   "recinto": "Módulo Secretaría-Admisión-Recaudación",
   "cod": "23.1.3",
   "alt": [],
   "cod_orig": "23.1.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 300,
   "est": "HDS",
   "recinto": "Oficina Jefatura",
   "cod": "23.1.4",
   "alt": [],
   "cod_orig": "23.1.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 301,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "23.2.1",
   "alt": [],
   "cod_orig": "23.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 302,
   "est": "HDS",
   "recinto": "Consulta Médica",
   "cod": "23.2.4",
   "alt": [],
   "cod_orig": "23.2.4",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 303,
   "est": "HDS",
   "recinto": "Consulta Enfermería",
   "cod": "23.2.5",
   "alt": [],
   "cod_orig": "23.2.5",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 304,
   "est": "HDS",
   "recinto": "Consulta Psicología",
   "cod": "23.2.6",
   "alt": [],
   "cod_orig": "23.2.6",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 305,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "45.1.2",
   "alt": [],
   "cod_orig": "45.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 306,
   "est": "HDS",
   "recinto": "Oficina Jefe",
   "cod": "45.1.4",
   "alt": [],
   "cod_orig": "45.1.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 307,
   "est": "HDS",
   "recinto": "Oficina Subjefe Calidad",
   "cod": "45.1.5",
   "alt": [],
   "cod_orig": "45.1.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 308,
   "est": "HDS",
   "recinto": "Entrega Muestras",
   "cod": "45.1.7",
   "alt": [],
   "cod_orig": "45.1.7",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 309,
   "est": "HDS",
   "recinto": "Oficina Encargado",
   "cod": "45.3.1",
   "alt": [],
   "cod_orig": "45.3.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 310,
   "est": "HDS",
   "recinto": "Módulo Secretaría Recepción Espera",
   "cod": "46.1.1",
   "alt": [],
   "cod_orig": "46.1.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 311,
   "est": "HDS",
   "recinto": "Módulo Secretaría",
   "cod": "46.1.2",
   "alt": [],
   "cod_orig": "46.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 312,
   "est": "HDS",
   "recinto": "Oficina Médico Patólogo Jefe",
   "cod": "46.1.3",
   "alt": [],
   "cod_orig": "46.1.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 313,
   "est": "HDS",
   "recinto": "Estación Trabajo Médicos Patólogos",
   "cod": "46.1.5",
   "alt": [],
   "cod_orig": "46.1.5",
   "tipo": "multi",
   "cant": 4,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 314,
   "est": "HDS",
   "recinto": "Oficina Patólogo",
   "cod": "46.1.6",
   "alt": [],
   "cod_orig": "46.1.6",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 315,
   "est": "HDS",
   "recinto": "Estación Trabajo Médicos Becados",
   "cod": "46.1.8",
   "alt": [],
   "cod_orig": "46.1.8",
   "tipo": "multi",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 316,
   "est": "HDS",
   "recinto": "Sala Trabajo Administrativo",
   "cod": "46.1.9",
   "alt": [],
   "cod_orig": "46.1.9",
   "tipo": "mfp",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 317,
   "est": "HDS",
   "recinto": "Oficina Coordinadora Corneas",
   "cod": "46.6.4",
   "alt": [],
   "cod_orig": "46.6.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 318,
   "est": "HDS",
   "recinto": "Preparación Entrega Fallecidos",
   "cod": "46.6.5",
   "alt": [],
   "cod_orig": "46.6.5",
   "tipo": "multi",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 319,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "48.1.2",
   "alt": [],
   "cod_orig": "48.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 320,
   "est": "HDS",
   "recinto": "Entrega Resultados",
   "cod": "48.1.3",
   "alt": [],
   "cod_orig": "48.1.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 321,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "48.2.3",
   "alt": [],
   "cod_orig": "48.2.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 322,
   "est": "HDS",
   "recinto": "Sala Informes",
   "cod": "48.2.5",
   "alt": [],
   "cod_orig": "48.2.5",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 323,
   "est": "HDS",
   "recinto": "Admin., Recepción, Muestras, Secretaria",
   "cod": "49.1.1",
   "alt": [],
   "cod_orig": "49.1.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 324,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "49.1.5",
   "alt": [],
   "cod_orig": "49.1.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 325,
   "est": "HDS",
   "recinto": "Despacho Transfusiones",
   "cod": "49.3.1",
   "alt": [],
   "cod_orig": "49.3.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha de Enchufe"
  },
  {
   "fila": 326,
   "est": "HDS",
   "recinto": "Oficina Calidad",
   "cod": "49.3.4",
   "alt": [],
   "cod_orig": "49.3.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 327,
   "est": "HDS",
   "recinto": "Secretaría Recepción",
   "cod": "50.1.1",
   "alt": [],
   "cod_orig": "50.1.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 328,
   "est": "HDS",
   "recinto": "Oficina Enfermera Supervisora",
   "cod": "50.1.3",
   "alt": [],
   "cod_orig": "50.1.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 329,
   "est": "HDS",
   "recinto": "Recepción",
   "cod": "50.4.0",
   "alt": [],
   "cod_orig": "50.4.0",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 330,
   "est": "HDS",
   "recinto": "Preparación",
   "cod": "50.6.2",
   "alt": [],
   "cod_orig": "50.6.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 331,
   "est": "HDS",
   "recinto": "Empaquetado",
   "cod": "50.6.4",
   "alt": [],
   "cod_orig": "50.6.4",
   "tipo": "multi",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 332,
   "est": "HDS",
   "recinto": "Oficina Egreso",
   "cod": "51.9",
   "alt": [],
   "cod_orig": "51.9",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 333,
   "est": "HDS",
   "recinto": "Área Recepción",
   "cod": "52.2",
   "alt": [],
   "cod_orig": "52.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 334,
   "est": "HDS",
   "recinto": "Módulo Secretaría",
   "cod": "52.3",
   "alt": [],
   "cod_orig": "52.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 335,
   "est": "HDS",
   "recinto": "Oficina Farmaceutico Jefe Logistica",
   "cod": "52.5",
   "alt": [],
   "cod_orig": "52.5",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 336,
   "est": "HDS",
   "recinto": "Estaciones Trabajo Administrativo",
   "cod": "52.6",
   "alt": [],
   "cod_orig": "52.6",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 337,
   "est": "HDS",
   "recinto": "Estaciones Trabajo Profesional",
   "cod": "52.7",
   "alt": [],
   "cod_orig": "52.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 338,
   "est": "HDS",
   "recinto": "Módulo Secretaría Recepción Espera",
   "cod": "53.1.1",
   "alt": [],
   "cod_orig": "53.1.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 339,
   "est": "HDS",
   "recinto": "Oficina Jefatura Bodegas Logísticas",
   "cod": "53.1.2",
   "alt": [],
   "cod_orig": "53.1.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 340,
   "est": "HDS",
   "recinto": "Estaciones Trabajo Administrativo",
   "cod": "53.1.3",
   "alt": [],
   "cod_orig": "53.1.3",
   "tipo": "mfp",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 341,
   "est": "HDS",
   "recinto": "Módulo Secretaría",
   "cod": "54.1.1",
   "alt": [],
   "cod_orig": "54.1.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 342,
   "est": "HDS",
   "recinto": "Oficina Jefe Farmacia",
   "cod": "54.1.2",
   "alt": [],
   "cod_orig": "54.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 343,
   "est": "HDS",
   "recinto": "Estaciones Trabajo Profesional",
   "cod": "54.1.4",
   "alt": [],
   "cod_orig": "54.1.4",
   "tipo": "mfp",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 344,
   "est": "HDS",
   "recinto": "Preparación Dispensación Dosis Unitaria",
   "cod": "54.3.1",
   "alt": [],
   "cod_orig": "54.3.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 345,
   "est": "HDS",
   "recinto": "Sala Reenvasado DU",
   "cod": "54.3.2",
   "alt": [],
   "cod_orig": "54.3.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 346,
   "est": "HDS",
   "recinto": "Oficina Químico",
   "cod": "55.1.1",
   "alt": [],
   "cod_orig": "55.1.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 347,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "55.2.1",
   "alt": [],
   "cod_orig": "55.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 348,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "55.3.1",
   "alt": [],
   "cod_orig": "55.3.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 361,
   "est": "AMBOS",
   "recinto": "Central Alimentación - Oficina",
   "cod": "67.2.5",
   "alt": [],
   "cod_orig": "67.2.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 362,
   "est": "AMBOS",
   "recinto": "Oficina",
   "cod": "67.2.1",
   "alt": [],
   "cod_orig": "67.2.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 363,
   "est": "AMBOS",
   "recinto": "Rpería - Of. Contrato Ext",
   "cod": "69.1.1",
   "alt": [],
   "cod_orig": "69.1.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 364,
   "est": "AMBOS",
   "recinto": "Área de Recepción y Registro Logística",
   "cod": "85.1.1.1",
   "alt": [],
   "cod_orig": "85.1.1.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 365,
   "est": "AMBOS",
   "recinto": "Secretaría Logistica",
   "cod": "85.1.2",
   "alt": [],
   "cod_orig": "85.1.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 366,
   "est": "AMBOS",
   "recinto": "Oficina Jefe Serv.Logística",
   "cod": "85.1.3",
   "alt": [],
   "cod_orig": "85.1.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 367,
   "est": "AMBOS",
   "recinto": "Estaciones de Trabajo Administrativo (8)",
   "cod": "85.1.4",
   "alt": [],
   "cod_orig": "85.1.4",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 368,
   "est": "AMBOS",
   "recinto": "Estaciones de Trabajo Profesionales (3)",
   "cod": "85.1.5",
   "alt": [],
   "cod_orig": "85.1.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 369,
   "est": "AMBOS",
   "recinto": "Oficina Funcinarios",
   "cod": "85.1.8",
   "alt": [],
   "cod_orig": "85.1.8",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 370,
   "est": "AMBOS",
   "recinto": "Módulo Secretaria/Receoción/ Espera",
   "cod": "85.2.1",
   "alt": [],
   "cod_orig": "85.2.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 371,
   "est": "AMBOS",
   "recinto": "Oficina Jefe Bodegas Centralizadas",
   "cod": "85.2.2",
   "alt": [],
   "cod_orig": "85.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 372,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "1.1",
   "alt": [],
   "cod_orig": "1.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 373,
   "est": "HDS",
   "recinto": "Entrega Exámenes",
   "cod": "2.1.4",
   "alt": [],
   "cod_orig": "2.1.4",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 374,
   "est": "HDS",
   "recinto": "Recepción",
   "cod": "2.2.2",
   "alt": [],
   "cod_orig": "2.2.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 375,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "2.2.4",
   "alt": [],
   "cod_orig": "2.2.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 376,
   "est": "HDS",
   "recinto": "Atención Usuarios",
   "cod": "2.2.6",
   "alt": [],
   "cod_orig": "2.2.6",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 377,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "2.2.7",
   "alt": [],
   "cod_orig": "2.2.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 378,
   "est": "HDS",
   "recinto": "Asistentes Sociales",
   "cod": "2.3.1",
   "alt": [],
   "cod_orig": "2.3.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 379,
   "est": "HDS",
   "recinto": "Admisión/ Recaudación",
   "cod": "13.1.5",
   "alt": [],
   "cod_orig": "13.1.5",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 380,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "13.1.6",
   "alt": [],
   "cod_orig": "13.1.6",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 381,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "13.1.7",
   "alt": [],
   "cod_orig": "13.1.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 382,
   "est": "HDS",
   "recinto": "Coordinación Médica",
   "cod": "13.1.9",
   "alt": [],
   "cod_orig": "13.1.9",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 383,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "13.1.10",
   "alt": [],
   "cod_orig": "13.1.10",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 384,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "13.2.1",
   "alt": [],
   "cod_orig": "13.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 385,
   "est": "HDS",
   "recinto": "Procedimiento Oftalmológico",
   "cod": "13.3.1",
   "alt": [],
   "cod_orig": "13.3.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 386,
   "est": "HDS",
   "recinto": "Procedimiento Oftalmológico",
   "cod": "13.3.2",
   "alt": [],
   "cod_orig": "13.3.2",
   "tipo": "mono",
   "cant": 7,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 387,
   "est": "HDS",
   "recinto": "Procedimiento Glaucoma",
   "cod": "13.3.5",
   "alt": [],
   "cod_orig": "13.3.5",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 388,
   "est": "HDS",
   "recinto": "Procedimiento cornea",
   "cod": "13.3.6",
   "alt": [],
   "cod_orig": "13.3.6",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 389,
   "est": "HDS",
   "recinto": "Procedimiento Retina",
   "cod": "13.3.7",
   "alt": [],
   "cod_orig": "13.3.7",
   "tipo": "mono",
   "cant": 4,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 390,
   "est": "HDS",
   "recinto": "Procedimiento orbita y protesis",
   "cod": "13.3.8",
   "alt": [],
   "cod_orig": "13.3.8",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 391,
   "est": "HDS",
   "recinto": "Procedimiento Úvea y V.I.H.",
   "cod": "13.3.9",
   "alt": [],
   "cod_orig": "13.3.9",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 392,
   "est": "HDS",
   "recinto": "Procedimiento baja visión",
   "cod": "13.3.10",
   "alt": [],
   "cod_orig": "13.3.10",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 393,
   "est": "HDS",
   "recinto": "Procedimiento TM cornea",
   "cod": "13.4.1",
   "alt": [],
   "cod_orig": "13.4.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 394,
   "est": "HDS",
   "recinto": "Procedimiento TM glaucoma",
   "cod": "13.4.2",
   "alt": [],
   "cod_orig": "13.4.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 395,
   "est": "HDS",
   "recinto": "Procedimiento TM retina",
   "cod": "13.4.3",
   "alt": [],
   "cod_orig": "13.4.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 396,
   "est": "HDS",
   "recinto": "Procedimiento Ecografía Ocular",
   "cod": "13.4.4",
   "alt": [],
   "cod_orig": "13.4.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 397,
   "est": "HDS",
   "recinto": "Procedimiento Ecografía Ocular",
   "cod": "13.4.4_B",
   "alt": [],
   "cod_orig": "13.4.4_B",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 398,
   "est": "HDS",
   "recinto": "Procedimiento electrofisiología",
   "cod": "13.4.5",
   "alt": [],
   "cod_orig": "13.4.5",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 399,
   "est": "HDS",
   "recinto": "Procedimiento Estrabismo Adulto",
   "cod": "13.4.6",
   "alt": [],
   "cod_orig": "13.4.6",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 400,
   "est": "HDS",
   "recinto": "Admisión/ Recaudación",
   "cod": "16.1.3",
   "alt": [],
   "cod_orig": "16.1.3",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 401,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "16.1.4",
   "alt": [],
   "cod_orig": "16.1.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 402,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "16.1.5",
   "alt": [],
   "cod_orig": "16.1.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 403,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "16.1.7",
   "alt": [],
   "cod_orig": "16.1.7",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 404,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "16.2.1",
   "alt": [],
   "cod_orig": "16.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 405,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "16.2.4",
   "alt": [],
   "cod_orig": "16.2.4",
   "tipo": "mono",
   "cant": 6,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 406,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "16.2.5",
   "alt": [],
   "cod_orig": "16.2.5",
   "tipo": "mono",
   "cant": 8,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 407,
   "est": "HDS",
   "recinto": "Consulta Salud Mental",
   "cod": "16.2.6",
   "alt": [],
   "cod_orig": "16.2.6",
   "tipo": "mono",
   "cant": 8,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 408,
   "est": "HDS",
   "recinto": "Procedimiento Enfermería",
   "cod": "16.2.7",
   "alt": [],
   "cod_orig": "16.2.7",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 409,
   "est": "HDS",
   "recinto": "Recepción",
   "cod": "20.1.1",
   "alt": [],
   "cod_orig": "20.1.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 410,
   "est": "HDS",
   "recinto": "Jefe Servicio y Enfermera Coordinadora",
   "cod": "20.2.2",
   "alt": [],
   "cod_orig": "20.2.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 411,
   "est": "HDS",
   "recinto": "Recepción",
   "cod": "24.1.4",
   "alt": [],
   "cod_orig": "24.1.4",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 412,
   "est": "HDS",
   "recinto": "Enfermera",
   "cod": "24.1.5",
   "alt": [],
   "cod_orig": "24.1.5",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 413,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "24.1.6.1",
   "alt": [],
   "cod_orig": "24.1.6.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 414,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "24.1.11.1",
   "alt": [],
   "cod_orig": "24.1.11.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 415,
   "est": "HDS",
   "recinto": "Recepción",
   "cod": "25.1.3",
   "alt": [],
   "cod_orig": "25.1.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 416,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "25.1.5",
   "alt": [],
   "cod_orig": "25.1.5",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 417,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "25.1.6",
   "alt": [],
   "cod_orig": "25.1.6",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 418,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "25.3.2",
   "alt": [],
   "cod_orig": "25.3.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 419,
   "est": "HDS",
   "recinto": "Atención Pacientes",
   "cod": "25.3.3",
   "alt": [],
   "cod_orig": "25.3.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 420,
   "est": "HDS",
   "recinto": "Entrega Medicamentos",
   "cod": "25.3.4",
   "alt": [],
   "cod_orig": "25.3.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 421,
   "est": "HDS",
   "recinto": "Admisión/Recaudación",
   "cod": "26.1.4",
   "alt": [],
   "cod_orig": "26.1.4",
   "tipo": "multi",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 422,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "26.1.5",
   "alt": [],
   "cod_orig": "26.1.5",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 423,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "26.1.6",
   "alt": [],
   "cod_orig": "26.1.6",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 424,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "26.2.3",
   "alt": [],
   "cod_orig": "26.2.3",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 425,
   "est": "HDS",
   "recinto": "Sala espera",
   "cod": "26.2.7",
   "alt": [],
   "cod_orig": "26.2.7",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 426,
   "est": "HDS",
   "recinto": "Procedimiento Alcoholemia",
   "cod": "26.2.8",
   "alt": [],
   "cod_orig": "26.2.8",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 427,
   "est": "HDS",
   "recinto": "Estación de Enfermería",
   "cod": "26.4.5",
   "alt": [],
   "cod_orig": "26.4.5",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha de Enchufe"
  },
  {
   "fila": 428,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "26.6",
   "alt": [],
   "cod_orig": "26.6",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 429,
   "est": "HDS",
   "recinto": "Procedimientos Yeso",
   "cod": "26.7",
   "alt": [],
   "cod_orig": "26.7",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 430,
   "est": "HDS",
   "recinto": "Admisión/Recaudación",
   "cod": "26.12.1.2",
   "alt": [],
   "cod_orig": "26.12.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 431,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "26.12.1.3",
   "alt": [],
   "cod_orig": "26.12.1.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 432,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "26.12.1.4",
   "alt": [],
   "cod_orig": "26.12.1.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 433,
   "est": "HDS",
   "recinto": "Ingreso/Egresos UTO",
   "cod": "26.12.2.7",
   "alt": [],
   "cod_orig": "26.12.2.7",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 434,
   "est": "HDS",
   "recinto": "Recepción",
   "cod": "31.1.2",
   "alt": [],
   "cod_orig": "31.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 435,
   "est": "HDS",
   "recinto": "Recepción",
   "cod": "43.1.2",
   "alt": [],
   "cod_orig": "43.1.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 436,
   "est": "HDS",
   "recinto": "Enfermera Supervisora",
   "cod": "43.2.1",
   "alt": [],
   "cod_orig": "43.2.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 437,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "43.2.4",
   "alt": [],
   "cod_orig": "43.2.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 438,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "43.3.1",
   "alt": [],
   "cod_orig": "43.3.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 439,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "43.3.7",
   "alt": [],
   "cod_orig": "43.3.7",
   "tipo": "multi",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 440,
   "est": "HDS",
   "recinto": "Entrevista",
   "cod": "43.7.1",
   "alt": [],
   "cod_orig": "43.7.1",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 441,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "44.1.1",
   "alt": [],
   "cod_orig": "44.1.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 442,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "44.1.2",
   "alt": [],
   "cod_orig": "44.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 443,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "44.2.2",
   "alt": [],
   "cod_orig": "44.2.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 444,
   "est": "HDS",
   "recinto": "Enfermera Supervisora",
   "cod": "44.3.1",
   "alt": [],
   "cod_orig": "44.3.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 445,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "44.4.1",
   "alt": [],
   "cod_orig": "44.4.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 446,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "44.4.7",
   "alt": [],
   "cod_orig": "44.4.7",
   "tipo": "multi",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 447,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "44.5.2",
   "alt": [],
   "cod_orig": "44.5.2",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 448,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "44.5.3",
   "alt": [],
   "cod_orig": "44.5.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 449,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "47.1.2",
   "alt": [],
   "cod_orig": "47.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 450,
   "est": "HDS",
   "recinto": "Entrega Resultados",
   "cod": "47.1.3",
   "alt": [],
   "cod_orig": "47.1.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 451,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "47.2.1",
   "alt": [],
   "cod_orig": "47.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 452,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "47.2.2",
   "alt": [],
   "cod_orig": "47.2.2",
   "tipo": "multi",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 453,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "47.2.5",
   "alt": [],
   "cod_orig": "47.2.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 454,
   "est": "HDS",
   "recinto": "Procesamiento Imágenes",
   "cod": "47.11.3",
   "alt": [],
   "cod_orig": "47.11.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 455,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "58.2.1",
   "alt": [],
   "cod_orig": "58.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 456,
   "est": "HDS",
   "recinto": "Jefe SOME",
   "cod": "58.2.2",
   "alt": [],
   "cod_orig": "58.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 457,
   "est": "HDS",
   "recinto": "Coordinacion Traslados",
   "cod": "58.2.3",
   "alt": [],
   "cod_orig": "58.2.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 458,
   "est": "HDS",
   "recinto": "Compra Extrasistema",
   "cod": "58.2.4",
   "alt": [],
   "cod_orig": "58.2.4",
   "tipo": "multi",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 459,
   "est": "HDS",
   "recinto": "Módulo Atención",
   "cod": "58.2.5",
   "alt": [],
   "cod_orig": "58.2.5",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 460,
   "est": "HDS",
   "recinto": "Recepción",
   "cod": "58.3.1",
   "alt": [],
   "cod_orig": "58.3.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 461,
   "est": "HDS",
   "recinto": "Oficina Accidentes",
   "cod": "58.3.3",
   "alt": [],
   "cod_orig": "58.3.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 462,
   "est": "HDS",
   "recinto": "Oficina Jefe Recaudación",
   "cod": "58.3.4",
   "alt": [],
   "cod_orig": "58.3.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 463,
   "est": "HDS",
   "recinto": "Oficina Emision de Cuentas",
   "cod": "58.3.5",
   "alt": [],
   "cod_orig": "58.3.5",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 464,
   "est": "HDS",
   "recinto": "Oficina Cuentas Pendientes",
   "cod": "58.3.6",
   "alt": [],
   "cod_orig": "58.3.6",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 465,
   "est": "HDS",
   "recinto": "Cobranzas",
   "cod": "58.3.7",
   "alt": [],
   "cod_orig": "58.3.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 466,
   "est": "HDS",
   "recinto": "Ingresos",
   "cod": "58.3.8",
   "alt": [],
   "cod_orig": "58.3.8",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 467,
   "est": "HDS",
   "recinto": "OIRS",
   "cod": "58.4.1",
   "alt": [],
   "cod_orig": "58.4.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 468,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "59.1",
   "alt": [],
   "cod_orig": "59.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 469,
   "est": "HDS",
   "recinto": "Módulo Orientación",
   "cod": "59.3",
   "alt": [],
   "cod_orig": "59.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 511,
   "est": "AMBOS",
   "recinto": "Secretaria",
   "cod": "81.1.1",
   "alt": [],
   "cod_orig": "81.1.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 512,
   "est": "HDS",
   "recinto": "Admisión/Recaudación",
   "cod": "6.1.2",
   "alt": [],
   "cod_orig": "6.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 513,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "6.2.1",
   "alt": [],
   "cod_orig": "6.2.1",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 514,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "6.2.2",
   "alt": [],
   "cod_orig": "6.2.2",
   "tipo": "mono",
   "cant": 11,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 515,
   "est": "HDS",
   "recinto": "Admisión/Recaudación",
   "cod": "7.1.2",
   "alt": [],
   "cod_orig": "7.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 516,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "7.2.1",
   "alt": [],
   "cod_orig": "7.2.1",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 517,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "7.2.2",
   "alt": [],
   "cod_orig": "7.2.2",
   "tipo": "mono",
   "cant": 4,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 518,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "7.2.3",
   "alt": [],
   "cod_orig": "7.2.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 519,
   "est": "HDS",
   "recinto": "Admisión/Recaudación",
   "cod": "8.1.2",
   "alt": [],
   "cod_orig": "8.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 520,
   "est": "HDS",
   "recinto": "Informes",
   "cod": "8.1.3",
   "alt": [],
   "cod_orig": "8.1.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 521,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "8.1.4",
   "alt": [],
   "cod_orig": "8.1.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 522,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "8.2.1",
   "alt": [],
   "cod_orig": "8.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 523,
   "est": "HDS",
   "recinto": "Admisión/Recaudación",
   "cod": "10.2",
   "alt": [],
   "cod_orig": "10.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 524,
   "est": "HDS",
   "recinto": "Enfermera",
   "cod": "10.2.1",
   "alt": [],
   "cod_orig": "10.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 525,
   "est": "HDS",
   "recinto": "Informes",
   "cod": "10.3",
   "alt": [],
   "cod_orig": "10.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 526,
   "est": "HDS",
   "recinto": "Admisión",
   "cod": "21.1.2",
   "alt": [],
   "cod_orig": "21.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 527,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "21.1.3",
   "alt": [],
   "cod_orig": "21.1.3",
   "tipo": "mono",
   "cant": 5,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 528,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "21.1.4",
   "alt": [],
   "cod_orig": "21.1.4",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 529,
   "est": "HDS",
   "recinto": "Coordinación General Trasplantes",
   "cod": "21.1.7",
   "alt": [],
   "cod_orig": "21.1.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 530,
   "est": "HDS",
   "recinto": "Coordinación Renal",
   "cod": "21.1.8a",
   "alt": [],
   "cod_orig": "21.1.8a",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 531,
   "est": "HDS",
   "recinto": "Coordinación Hepático",
   "cod": "21.1.8b",
   "alt": [],
   "cod_orig": "21.1.8b",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 532,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "21.1.11",
   "alt": [],
   "cod_orig": "21.1.11",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 533,
   "est": "HDS",
   "recinto": "Admisión",
   "cod": "22.1.2",
   "alt": [],
   "cod_orig": "22.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 534,
   "est": "HDS",
   "recinto": "Enfermera Jefe",
   "cod": "22.1.4",
   "alt": [],
   "cod_orig": "22.1.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 535,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "22.2.1",
   "alt": [],
   "cod_orig": "22.2.1",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 536,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "22.2.2",
   "alt": [],
   "cod_orig": "22.2.2",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 537,
   "est": "HDS",
   "recinto": "Consulta salud mental",
   "cod": "22.2.3",
   "alt": [],
   "cod_orig": "22.2.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 538,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "22.2.4",
   "alt": [],
   "cod_orig": "22.2.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 539,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "22.2.5",
   "alt": [],
   "cod_orig": "22.2.5",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 540,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "22.3.1",
   "alt": [],
   "cod_orig": "22.3.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 541,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "22.4.1",
   "alt": [],
   "cod_orig": "22.4.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 542,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "27.0.1",
   "alt": [],
   "cod_orig": "27.0.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 543,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "27.0.2",
   "alt": [],
   "cod_orig": "27.0.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 544,
   "est": "HDS",
   "recinto": "Entrevista",
   "cod": "27.1.2",
   "alt": [],
   "cod_orig": "27.1.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 545,
   "est": "HDS",
   "recinto": "Protocolos",
   "cod": "27.3.3",
   "alt": [],
   "cod_orig": "27.3.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 546,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "27.7.1",
   "alt": [],
   "cod_orig": "27.7.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 547,
   "est": "HDS",
   "recinto": "Protocolos",
   "cod": "28.3.3",
   "alt": [],
   "cod_orig": "28.3.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 548,
   "est": "HDS",
   "recinto": "Trabajo Enfermería",
   "cod": "28.11_T",
   "alt": [],
   "cod_orig": "28.11_T",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 549,
   "est": "HDS",
   "recinto": "Consulta",
   "cod": "29.1.2",
   "alt": [],
   "cod_orig": "29.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 550,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "29.3.2",
   "alt": [],
   "cod_orig": "29.3.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 551,
   "est": "HDS",
   "recinto": "Admisión/ Recaudación",
   "cod": "30.1.2",
   "alt": [],
   "cod_orig": "30.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 552,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "37.1.1.2",
   "alt": [],
   "cod_orig": "37.1.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 553,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "37.1.2.1",
   "alt": [],
   "cod_orig": "37.1.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 554,
   "est": "HDS",
   "recinto": "Enfermera Supervisora",
   "cod": "37.1.2.2",
   "alt": [],
   "cod_orig": "37.1.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 555,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "37.1.3.1",
   "alt": [],
   "cod_orig": "37.1.3.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 556,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "37.1.3.7",
   "alt": [],
   "cod_orig": "37.1.3.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 557,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "37.2.1.2",
   "alt": [],
   "cod_orig": "37.2.1.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 558,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "37.2.2.1",
   "alt": [],
   "cod_orig": "37.2.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 559,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "37.2.2.2",
   "alt": [],
   "cod_orig": "37.2.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 560,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "37.2.2.3",
   "alt": [],
   "cod_orig": "37.2.2.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 561,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "37.2.4.1",
   "alt": [],
   "cod_orig": "37.2.4.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 562,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "37.2.4.7",
   "alt": [],
   "cod_orig": "37.2.4.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 563,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "38.1.1",
   "alt": [],
   "cod_orig": "38.1.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 564,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "38.1.2",
   "alt": [],
   "cod_orig": "38.1.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 565,
   "est": "HDS",
   "recinto": "Enfermera Supervisora",
   "cod": "38.1.3",
   "alt": [],
   "cod_orig": "38.1.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 566,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "38.2.2",
   "alt": [],
   "cod_orig": "38.2.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 567,
   "est": "HDS",
   "recinto": "Enfermera",
   "cod": "38.3.3",
   "alt": [],
   "cod_orig": "38.3.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 568,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "38.4.1",
   "alt": [],
   "cod_orig": "38.4.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 569,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "38.4.7",
   "alt": [],
   "cod_orig": "38.4.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 570,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "39.1.2",
   "alt": [],
   "cod_orig": "39.1.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 571,
   "est": "HDS",
   "recinto": "Enfermera",
   "cod": "39.2.3",
   "alt": [],
   "cod_orig": "39.2.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 572,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "39.3.1",
   "alt": [],
   "cod_orig": "39.3.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 573,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "39.3.7",
   "alt": [],
   "cod_orig": "39.3.7",
   "tipo": "multi",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 574,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "40.1.2",
   "alt": [],
   "cod_orig": "40.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 575,
   "est": "HDS",
   "recinto": "Enfermera",
   "cod": "40.2.3",
   "alt": [],
   "cod_orig": "40.2.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 576,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "40.3.1",
   "alt": [],
   "cod_orig": "40.3.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 577,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "40.3.7",
   "alt": [],
   "cod_orig": "40.3.7",
   "tipo": "multi",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 578,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "41.1.2",
   "alt": [],
   "cod_orig": "41.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 579,
   "est": "HDS",
   "recinto": "Enfermera",
   "cod": "41.2.3",
   "alt": [],
   "cod_orig": "41.2.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 580,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "41.3.1",
   "alt": [],
   "cod_orig": "41.3.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 581,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "41.3.7",
   "alt": [],
   "cod_orig": "41.3.7",
   "tipo": "multi",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 604,
   "est": "HDS",
   "recinto": "Módulo Secretaría Admisión",
   "cod": "11.1.2",
   "alt": [],
   "cod_orig": "11.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 605,
   "est": "HDS",
   "recinto": "Sala Informes",
   "cod": "11.1.3",
   "alt": [],
   "cod_orig": "11.1.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 606,
   "est": "HDS",
   "recinto": "Oficina Jefe Neurología",
   "cod": "11.1.4",
   "alt": [],
   "cod_orig": "11.1.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 607,
   "est": "HDS",
   "recinto": "Secretaría Neuro.",
   "cod": "11.1.4.1",
   "alt": [],
   "cod_orig": "11.1.4.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 608,
   "est": "HDS",
   "recinto": "Estaciones Trabajo Neurólogos",
   "cod": "11.1.5",
   "alt": [],
   "cod_orig": "11.1.5",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 609,
   "est": "HDS",
   "recinto": "Box Consulta Médica",
   "cod": "11.2.1",
   "alt": [],
   "cod_orig": "11.2.1",
   "tipo": "mono",
   "cant": 8,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 610,
   "est": "HDS",
   "recinto": "Box Consulta Psicólogo",
   "cod": "11.2.2",
   "alt": [],
   "cod_orig": "11.2.2",
   "tipo": "mono",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 611,
   "est": "HDS",
   "recinto": "Box Fonoaudiólogo",
   "cod": "11.2.3",
   "alt": [],
   "cod_orig": "11.2.3",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 612,
   "est": "HDS",
   "recinto": "Box Enfermería",
   "cod": "11.2.4",
   "alt": [],
   "cod_orig": "11.2.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 613,
   "est": "HDS",
   "recinto": "Secretaría/Admisión",
   "cod": "12.1.2",
   "alt": [],
   "cod_orig": "12.1.2",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 614,
   "est": "HDS",
   "recinto": "Oficina Secretaría",
   "cod": "12.1.3",
   "alt": [],
   "cod_orig": "12.1.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 615,
   "est": "HDS",
   "recinto": "Estaciones Trabajo Odontólogico",
   "cod": "12.1.4",
   "alt": [],
   "cod_orig": "12.1.4",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 616,
   "est": "HDS",
   "recinto": "Box Periodoncia",
   "cod": "12.2.1",
   "alt": [],
   "cod_orig": "12.2.1",
   "tipo": "mono",
   "cant": 4,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 617,
   "est": "HDS",
   "recinto": "Box Disfución",
   "cod": "12.2.2",
   "alt": [],
   "cod_orig": "12.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 618,
   "est": "HDS",
   "recinto": "Box Prótesis Removible",
   "cod": "12.2.3",
   "alt": [],
   "cod_orig": "12.2.3",
   "tipo": "mono",
   "cant": 6,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 619,
   "est": "HDS",
   "recinto": "Box Operatoria",
   "cod": "12.2.4",
   "alt": [],
   "cod_orig": "12.2.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 620,
   "est": "HDS",
   "recinto": "Box Cirugía Bucal (diagnóstico)",
   "cod": "12.2.5",
   "alt": [],
   "cod_orig": "12.2.5",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 621,
   "est": "HDS",
   "recinto": "Box Endodoncia (3 sillones)",
   "cod": "12.2.6",
   "alt": [],
   "cod_orig": "12.2.6",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 622,
   "est": "HDS",
   "recinto": "Otros recintos asistenciales (Menos Critica)",
   "cod": "12.2.7",
   "alt": [],
   "cod_orig": "12.2.7",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 623,
   "est": "HDS",
   "recinto": "Sala informes RX 3",
   "cod": "12.2.12",
   "alt": [],
   "cod_orig": "12.2.12",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 624,
   "est": "HDS",
   "recinto": "Secretaría-Adm.-Rec.",
   "cod": "14.1.2",
   "alt": [],
   "cod_orig": "14.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 625,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "14.1.3",
   "alt": [],
   "cod_orig": "14.1.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 626,
   "est": "HDS",
   "recinto": "Oficina Jefe Otorrino",
   "cod": "14.1.4",
   "alt": [],
   "cod_orig": "14.1.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 627,
   "est": "HDS",
   "recinto": "Estac. Trabajo Prof.",
   "cod": "14.1.6",
   "alt": [],
   "cod_orig": "14.1.6",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 628,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "14.2.1",
   "alt": [],
   "cod_orig": "14.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 629,
   "est": "HDS",
   "recinto": "Box Consulta Médica",
   "cod": "14.2.5",
   "alt": [],
   "cod_orig": "14.2.5",
   "tipo": "mono",
   "cant": 6,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 630,
   "est": "HDS",
   "recinto": "Box Fonoaudiólogo",
   "cod": "14.2.8",
   "alt": [],
   "cod_orig": "14.2.8",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 631,
   "est": "HDS",
   "recinto": "Otros Procedimientos",
   "cod": "14.2.12",
   "alt": [],
   "cod_orig": "14.2.12",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 632,
   "est": "HDS",
   "recinto": "Secr.-Adm.-Rec.",
   "cod": "17.1.2",
   "alt": [],
   "cod_orig": "17.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 633,
   "est": "HDS",
   "recinto": "Recepción ETS",
   "cod": "17.1.3",
   "alt": [],
   "cod_orig": "17.1.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 634,
   "est": "HDS",
   "recinto": "Secretaría Servico",
   "cod": "17.1.5",
   "alt": [],
   "cod_orig": "17.1.5",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 635,
   "est": "HDS",
   "recinto": "Jefe Servicio",
   "cod": "17.1.7",
   "alt": [],
   "cod_orig": "17.1.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 636,
   "est": "HDS",
   "recinto": "Estación Trabajo Profesionales",
   "cod": "17.1.9",
   "alt": [],
   "cod_orig": "17.1.9",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 637,
   "est": "HDS",
   "recinto": "Estac. Enferm. Area Amb.",
   "cod": "17.2.1",
   "alt": [],
   "cod_orig": "17.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 638,
   "est": "HDS",
   "recinto": "Consultas Ambulatorias",
   "cod": "17.2.5",
   "alt": [],
   "cod_orig": "17.2.5",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 639,
   "est": "HDS",
   "recinto": "Box Dermatología",
   "cod": "17.2.6",
   "alt": [],
   "cod_orig": "17.2.6",
   "tipo": "mono",
   "cant": 7,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 640,
   "est": "HDS",
   "recinto": "Consultas Ambulatorias",
   "cod": "17.2.7",
   "alt": [],
   "cod_orig": "17.2.7",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 641,
   "est": "HDS",
   "recinto": "Box Enfermería",
   "cod": "17.2.8",
   "alt": [],
   "cod_orig": "17.2.8",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 642,
   "est": "HDS",
   "recinto": "Estudios Dermatológicos",
   "cod": "17.3.2",
   "alt": [],
   "cod_orig": "17.3.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 643,
   "est": "HDS",
   "recinto": "Fototerapia y PUVA",
   "cod": "17.3.4",
   "alt": [],
   "cod_orig": "17.3.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 644,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "31.2.1",
   "alt": [],
   "cod_orig": "31.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 645,
   "est": "HDS",
   "recinto": "Oficina Enfermera Supervisora",
   "cod": "31.2.2",
   "alt": [],
   "cod_orig": "31.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 646,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "31.3.1",
   "alt": [],
   "cod_orig": "31.3.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 647,
   "est": "HDS",
   "recinto": "Trabajo Médico",
   "cod": "31.3.7",
   "alt": [],
   "cod_orig": "31.3.7",
   "tipo": "multi",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 648,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "32.1.2",
   "alt": [],
   "cod_orig": "32.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 649,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "32.2.1",
   "alt": [],
   "cod_orig": "32.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 650,
   "est": "HDS",
   "recinto": "Oficina Enfermera Supervisora",
   "cod": "32.2.2",
   "alt": [],
   "cod_orig": "32.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 651,
   "est": "HDS",
   "recinto": "Sala Trabajo",
   "cod": "32.2.11",
   "alt": [],
   "cod_orig": "32.2.11",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 652,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "32.3.1",
   "alt": [],
   "cod_orig": "32.3.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 653,
   "est": "HDS",
   "recinto": "Trabajo Médico",
   "cod": "32.3.7",
   "alt": [],
   "cod_orig": "32.3.7",
   "tipo": "multi",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 654,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "33.1.2",
   "alt": [],
   "cod_orig": "33.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 655,
   "est": "HDS",
   "recinto": "Módulo Secretaría",
   "cod": "33.2.1",
   "alt": [],
   "cod_orig": "33.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 656,
   "est": "HDS",
   "recinto": "Oficina Enfermera Supervisora",
   "cod": "33.2.2",
   "alt": [],
   "cod_orig": "33.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 657,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "33.3.1",
   "alt": [],
   "cod_orig": "33.3.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 658,
   "est": "HDS",
   "recinto": "Trabajo Médico",
   "cod": "33.3.7",
   "alt": [],
   "cod_orig": "33.3.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 659,
   "est": "HDS",
   "recinto": "Área de Formación (ud. Nº3)",
   "cod": "33.X",
   "alt": [],
   "cod_orig": "33.X",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 660,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "42.1.2",
   "alt": [],
   "cod_orig": "42.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 661,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "42.2.1",
   "alt": [],
   "cod_orig": "42.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 662,
   "est": "HDS",
   "recinto": "Oficina Enfermera Supervisora",
   "cod": "42.2.2",
   "alt": [],
   "cod_orig": "42.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 663,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "42.3.1",
   "alt": [],
   "cod_orig": "42.3.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 664,
   "est": "HDS",
   "recinto": "Estación Trabajo Médico",
   "cod": "42.3.7",
   "alt": [],
   "cod_orig": "42.3.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 670,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "34.1.2",
   "alt": [],
   "cod_orig": "34.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 671,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "34.2.1",
   "alt": [],
   "cod_orig": "34.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 672,
   "est": "HDS",
   "recinto": "Oficina Enfermera Supervisora",
   "cod": "34.2.2",
   "alt": [],
   "cod_orig": "34.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 673,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "34.3.1",
   "alt": [],
   "cod_orig": "34.3.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 674,
   "est": "HDS",
   "recinto": "Trabajo Médico",
   "cod": "34.3.7",
   "alt": [],
   "cod_orig": "34.3.7",
   "tipo": "multi",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 675,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "35.1.2",
   "alt": [],
   "cod_orig": "35.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 676,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "35.2.1",
   "alt": [],
   "cod_orig": "35.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 677,
   "est": "HDS",
   "recinto": "Oficina Enfermera Supervisora",
   "cod": "35.2.2",
   "alt": [],
   "cod_orig": "35.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 678,
   "est": "HDS",
   "recinto": "Sala Trabajo",
   "cod": "35.2.11",
   "alt": [],
   "cod_orig": "35.2.11",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 679,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "35.3.1",
   "alt": [],
   "cod_orig": "35.3.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 680,
   "est": "HDS",
   "recinto": "Trabajo Médico",
   "cod": "35.3.7",
   "alt": [],
   "cod_orig": "35.3.7",
   "tipo": "multi",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 681,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "36.1.2",
   "alt": [],
   "cod_orig": "36.1.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 682,
   "est": "HDS",
   "recinto": "Módulo Secretaría",
   "cod": "36.2.1",
   "alt": [],
   "cod_orig": "36.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 683,
   "est": "HDS",
   "recinto": "Oficina Enfermera Supervisora",
   "cod": "36.2.2",
   "alt": [],
   "cod_orig": "36.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 684,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "36.3.1",
   "alt": [],
   "cod_orig": "36.3.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 685,
   "est": "HDS",
   "recinto": "Trabajo Médico",
   "cod": "36.3.7",
   "alt": [],
   "cod_orig": "36.3.7",
   "tipo": "multi",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 686,
   "est": "HDS",
   "recinto": "Recepción Orientación",
   "cod": "42.1.2",
   "alt": [],
   "cod_orig": "42.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 687,
   "est": "HDS",
   "recinto": "Oficina Enfermera Supervisora",
   "cod": "42.2.2",
   "alt": [],
   "cod_orig": "42.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 688,
   "est": "HDS",
   "recinto": "Estación Enfermería",
   "cod": "42.3.1",
   "alt": [],
   "cod_orig": "42.3.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 689,
   "est": "HDS",
   "recinto": "Secretaría Recep",
   "cod": "56.1.2",
   "alt": [],
   "cod_orig": "56.1.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 690,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "56.1.3",
   "alt": [],
   "cod_orig": "56.1.3",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 691,
   "est": "HDS",
   "recinto": "Oficina Partes",
   "cod": "56.2.2",
   "alt": [],
   "cod_orig": "56.2.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 692,
   "est": "HDS",
   "recinto": "Director",
   "cod": "56.2.4",
   "alt": [],
   "cod_orig": "56.2.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 693,
   "est": "HDS",
   "recinto": "Subdirector Médico",
   "cod": "56.3.1",
   "alt": [],
   "cod_orig": "56.3.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 694,
   "est": "HDS",
   "recinto": "Subdirector Administrativo",
   "cod": "56.3.2",
   "alt": [],
   "cod_orig": "56.3.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 695,
   "est": "HDS",
   "recinto": "Subdirectora Enfer./Cuid.",
   "cod": "56.3.3",
   "alt": [],
   "cod_orig": "56.3.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 696,
   "est": "HDS",
   "recinto": "Oficina Subdirector de Operaciones",
   "cod": "56.3.4",
   "alt": [],
   "cod_orig": "56.3.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 697,
   "est": "HDS",
   "recinto": "Oficina Subdirector de Diagnóstico",
   "cod": "56.3.5",
   "alt": [],
   "cod_orig": "56.3.5",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 698,
   "est": "HDS",
   "recinto": "Oficina Gestión de camas",
   "cod": "56.4.1",
   "alt": [],
   "cod_orig": "56.4.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 699,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "56.5.1",
   "alt": [],
   "cod_orig": "56.5.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 700,
   "est": "HDS",
   "recinto": "Jefe Calidad y Seg.",
   "cod": "56.5.2",
   "alt": [],
   "cod_orig": "56.5.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 701,
   "est": "HDS",
   "recinto": "Ud Calidad/R. Clínico",
   "cod": "56.5.3",
   "alt": [],
   "cod_orig": "56.5.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 702,
   "est": "HDS",
   "recinto": "Ud Infecc./A. Salud",
   "cod": "56.5.4",
   "alt": [],
   "cod_orig": "56.5.4",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 703,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "56.7.1",
   "alt": [],
   "cod_orig": "56.7.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 704,
   "est": "HDS",
   "recinto": "Jefe Auditorías",
   "cod": "56.7.2",
   "alt": [],
   "cod_orig": "56.7.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 705,
   "est": "HDS",
   "recinto": "Oficina Auditorías",
   "cod": "56.7.3",
   "alt": [],
   "cod_orig": "56.7.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 706,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "56.8.1",
   "alt": [],
   "cod_orig": "56.8.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 707,
   "est": "HDS",
   "recinto": "Jefe Ud docente/Investigac.",
   "cod": "56.8.2",
   "alt": [],
   "cod_orig": "56.8.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 708,
   "est": "HDS",
   "recinto": "Trabajo Administrativo",
   "cod": "56.8.3",
   "alt": [],
   "cod_orig": "56.8.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 709,
   "est": "HDS",
   "recinto": "Oficina Jefatura Control Gestion Hospitalaria",
   "cod": "56.9.1",
   "alt": [],
   "cod_orig": "56.9.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 710,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "56.9.2",
   "alt": [],
   "cod_orig": "56.9.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 711,
   "est": "HDS",
   "recinto": "Oficina Jefe Análisis Clínicos",
   "cod": "56.10.1",
   "alt": [],
   "cod_orig": "56.10.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 712,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "56.10.2",
   "alt": [],
   "cod_orig": "56.10.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 713,
   "est": "HDS",
   "recinto": "Jefe Ud Gestión",
   "cod": "56.11.1",
   "alt": [],
   "cod_orig": "56.11.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 714,
   "est": "HDS",
   "recinto": "Trabajo y Ud Gestion",
   "cod": "56.11.2",
   "alt": [],
   "cod_orig": "56.11.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 715,
   "est": "HDS",
   "recinto": "Oficina Jefatura Ud.Estadística",
   "cod": "56.12.1",
   "alt": [],
   "cod_orig": "56.12.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 716,
   "est": "HDS",
   "recinto": "Estación Trabajo Registro Nacional Tumores",
   "cod": "56.12.2",
   "alt": [],
   "cod_orig": "56.12.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 717,
   "est": "HDS",
   "recinto": "Oficina Jefatura Estadística",
   "cod": "56.13.1",
   "alt": [],
   "cod_orig": "56.13.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 718,
   "est": "HDS",
   "recinto": "Estación Trabajo Estadística",
   "cod": "56.13.2",
   "alt": [],
   "cod_orig": "56.13.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 719,
   "est": "HDS",
   "recinto": "Oficina Jefatura Ges",
   "cod": "56.14.1",
   "alt": [],
   "cod_orig": "56.14.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 720,
   "est": "HDS",
   "recinto": "Estación Trabajo Monitor",
   "cod": "56.14.2",
   "alt": [],
   "cod_orig": "56.14.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 721,
   "est": "HDS",
   "recinto": "Digitación Ext. GES",
   "cod": "56.14.3",
   "alt": [],
   "cod_orig": "56.14.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 722,
   "est": "HDS",
   "recinto": "Oficina Comunicaciones",
   "cod": "56.15.1",
   "alt": [],
   "cod_orig": "56.15.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 723,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "56.16.1",
   "alt": [],
   "cod_orig": "56.16.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 724,
   "est": "HDS",
   "recinto": "Asesoría Legal",
   "cod": "56.16.2",
   "alt": [],
   "cod_orig": "56.16.2",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 725,
   "est": "HDS",
   "recinto": "Módulo Secretaría-Recepción-Espera",
   "cod": "57.1.2",
   "alt": [
    "57.1.3"
   ],
   "cod_orig": "57.1.2/57.1.3",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 726,
   "est": "HDS",
   "recinto": "Impresora",
   "cod": "57.1.4",
   "alt": [],
   "cod_orig": "57.1.4",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 727,
   "est": "HDS",
   "recinto": "Jefe Finanzas",
   "cod": "57.2.1",
   "alt": [],
   "cod_orig": "57.2.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 728,
   "est": "HDS",
   "recinto": "Jefe Contabilidad",
   "cod": "57.2.2",
   "alt": [],
   "cod_orig": "57.2.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 729,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "57.2.3",
   "alt": [],
   "cod_orig": "57.2.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 730,
   "est": "HDS",
   "recinto": "Tesorería",
   "cod": "57.2.4",
   "alt": [],
   "cod_orig": "57.2.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 731,
   "est": "HDS",
   "recinto": "Presupuesto",
   "cod": "57.2.5",
   "alt": [],
   "cod_orig": "57.2.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 732,
   "est": "HDS",
   "recinto": "Facturac/Cobranza",
   "cod": "57.2.6",
   "alt": [],
   "cod_orig": "57.2.6",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 733,
   "est": "HDS",
   "recinto": "Control Facturas",
   "cod": "57.2.7",
   "alt": [],
   "cod_orig": "57.2.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 734,
   "est": "HDS",
   "recinto": "Subdirector RR.HH.",
   "cod": "57.3.1",
   "alt": [],
   "cod_orig": "57.3.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 735,
   "est": "HDS",
   "recinto": "Subjefe RR.HH.",
   "cod": "57.3.2",
   "alt": [],
   "cod_orig": "57.3.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 736,
   "est": "HDS",
   "recinto": "Asistencia Social",
   "cod": "57.3.3",
   "alt": [],
   "cod_orig": "57.3.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 737,
   "est": "HDS",
   "recinto": "Psicologa Laboral",
   "cod": "57.3.4",
   "alt": [],
   "cod_orig": "57.3.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 738,
   "est": "HDS",
   "recinto": "Prevencion de Riesgos",
   "cod": "57.3.5",
   "alt": [],
   "cod_orig": "57.3.5",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 739,
   "est": "HDS",
   "recinto": "Jefe Capacitación",
   "cod": "57.3.6",
   "alt": [],
   "cod_orig": "57.3.6",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 740,
   "est": "HDS",
   "recinto": "Administrativo Capacitación",
   "cod": "57.3.7",
   "alt": [],
   "cod_orig": "57.3.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 741,
   "est": "HDS",
   "recinto": "RR.HH.",
   "cod": "57.3.8.1",
   "alt": [],
   "cod_orig": "57.3.8.1",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 742,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "57.4.2",
   "alt": [],
   "cod_orig": "57.4.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 743,
   "est": "HDS",
   "recinto": "Ud Informacion RRHH",
   "cod": "57.5.5",
   "alt": [],
   "cod_orig": "57.5.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 744,
   "est": "HDS",
   "recinto": "Secretaría y Recep.",
   "cod": "57.6.1.1",
   "alt": [],
   "cod_orig": "57.6.1.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 745,
   "est": "HDS",
   "recinto": "Oficina Jefe Servicios Generales",
   "cod": "57.6.1.2",
   "alt": [],
   "cod_orig": "57.6.1.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 746,
   "est": "HDS",
   "recinto": "Estaciones Trabajo Servicios Generales",
   "cod": "57.6.1.3",
   "alt": [],
   "cod_orig": "57.6.1.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 747,
   "est": "HDS",
   "recinto": "Secretaria/Recepción",
   "cod": "57.6.2.1",
   "alt": [],
   "cod_orig": "57.6.2.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 748,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "57.6.2.2",
   "alt": [],
   "cod_orig": "57.6.2.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 749,
   "est": "HDS",
   "recinto": "Secretaria/Recepción",
   "cod": "57.6.3.1",
   "alt": [],
   "cod_orig": "57.6.3.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 750,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "57.6.3.2",
   "alt": [],
   "cod_orig": "57.6.3.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 751,
   "est": "HDS",
   "recinto": "Secretaria/Recepción",
   "cod": "57.6.4.1",
   "alt": [],
   "cod_orig": "57.6.4.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 752,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "57.6.4.2",
   "alt": [],
   "cod_orig": "57.6.4.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 753,
   "est": "HDS",
   "recinto": "Estación Trabajo",
   "cod": "57.6.5.1",
   "alt": [],
   "cod_orig": "57.6.5.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "Pendiente",
   "obs": "Brecha Punto de Red"
  },
  {
   "fila": 754,
   "est": "HDS",
   "recinto": "Módulo Recepción",
   "cod": "60.1.1",
   "alt": [],
   "cod_orig": "60.1.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 755,
   "est": "HDS",
   "recinto": "Secretaría",
   "cod": "60.1.2",
   "alt": [],
   "cod_orig": "60.1.2",
   "tipo": "mfp",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 756,
   "est": "HDS",
   "recinto": "Jefe Medicina",
   "cod": "60.2.1",
   "alt": [],
   "cod_orig": "60.2.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 757,
   "est": "HDS",
   "recinto": "Jefes Sub Esp Med",
   "cod": "60.2.3",
   "alt": [],
   "cod_orig": "60.2.3",
   "tipo": "mono",
   "cant": 8,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 758,
   "est": "HDS",
   "recinto": "Cardiología",
   "cod": "60.3.1",
   "alt": [],
   "cod_orig": "60.3.1",
   "tipo": "multi",
   "cant": 2,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 759,
   "est": "HDS",
   "recinto": "Endocrinología",
   "cod": "60.3.2",
   "alt": [],
   "cod_orig": "60.3.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 760,
   "est": "HDS",
   "recinto": "Gastroenterología",
   "cod": "60.3.3",
   "alt": [],
   "cod_orig": "60.3.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 761,
   "est": "HDS",
   "recinto": "Hematología",
   "cod": "60.3.4",
   "alt": [],
   "cod_orig": "60.3.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 762,
   "est": "HDS",
   "recinto": "Infectología",
   "cod": "60.3.5",
   "alt": [],
   "cod_orig": "60.3.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 763,
   "est": "HDS",
   "recinto": "Nefrologia",
   "cod": "60.3.6",
   "alt": [],
   "cod_orig": "60.3.6",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 764,
   "est": "HDS",
   "recinto": "Nutrición Diabetes",
   "cod": "60.3.7",
   "alt": [],
   "cod_orig": "60.3.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 765,
   "est": "HDS",
   "recinto": "Reumatología",
   "cod": "60.3.8",
   "alt": [],
   "cod_orig": "60.3.8",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 766,
   "est": "HDS",
   "recinto": "Jefe Cirugía",
   "cod": "60.4.1",
   "alt": [],
   "cod_orig": "60.4.1",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 767,
   "est": "HDS",
   "recinto": "Jefe Área Quirurgica",
   "cod": "60.4.2",
   "alt": [],
   "cod_orig": "60.4.2",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 768,
   "est": "HDS",
   "recinto": "Jefe Traumatologia",
   "cod": "60.4.3",
   "alt": [],
   "cod_orig": "60.4.3",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 769,
   "est": "HDS",
   "recinto": "Jefe Urología",
   "cod": "60.4.4",
   "alt": [],
   "cod_orig": "60.4.4",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 770,
   "est": "HDS",
   "recinto": "Jefe Sub Esp. Quir.",
   "cod": "60.4.5_E",
   "alt": [],
   "cod_orig": "60.4.5_E",
   "tipo": "mono",
   "cant": 3,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 771,
   "est": "HDS",
   "recinto": "Subjefe Traumatología",
   "cod": "60.4.5_T",
   "alt": [],
   "cod_orig": "60.4.5_T",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 772,
   "est": "HDS",
   "recinto": "Subjefe Urología",
   "cod": "60.4.5_U",
   "alt": [],
   "cod_orig": "60.4.5_U",
   "tipo": "mono",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 773,
   "est": "HDS",
   "recinto": "Digestivo Alto y Bajo",
   "cod": "60.5.1",
   "alt": [],
   "cod_orig": "60.5.1",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 774,
   "est": "HDS",
   "recinto": "Vascular Periférico",
   "cod": "60.5.2",
   "alt": [],
   "cod_orig": "60.5.2",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 775,
   "est": "HDS",
   "recinto": "Hepatobiliar",
   "cod": "60.5.3",
   "alt": [],
   "cod_orig": "60.5.3",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 776,
   "est": "HDS",
   "recinto": "Traumatología",
   "cod": "60.5.4",
   "alt": [],
   "cod_orig": "60.5.4",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 777,
   "est": "HDS",
   "recinto": "Urología",
   "cod": "60.5.5",
   "alt": [],
   "cod_orig": "60.5.5",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 778,
   "est": "HDS",
   "recinto": "Oncología y Plástica",
   "cod": "60.5.6",
   "alt": [],
   "cod_orig": "60.5.6",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 779,
   "est": "HDS",
   "recinto": "Cabeza Cuello",
   "cod": "60.5.7",
   "alt": [],
   "cod_orig": "60.5.7",
   "tipo": "multi",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  },
  {
   "fila": 780,
   "est": "HDS",
   "recinto": "Biblioteca",
   "cod": "61.1",
   "alt": [],
   "cod_orig": "61.1",
   "tipo": "mfp",
   "cant": 1,
   "fact": "SI",
   "obs": ""
  }
 ]
};
